### ISSUE TITLE
RFC: AuthExchange - support handling typed GraphQL errors

### ISSUE THREAD

**Issue by crmitchelmore** [urql-graphql/urql#2707]
## Summary

When a schema implements strongly typed errors instead of using GraphQL errors, something like this https://blog.logrocket.com/handling-graphql-errors-like-a-champ-with-unions-and-interfaces/, there's no way to handle these with auth exchange.

In order to support these type of errors we should get a chance to inspect the result and refresh auth even when there are no GraphQL errors just data.

## Proposed Solution

Two options I see:

1: Update the calls to `didAuthError` to be called on all results and pass in data. This would likely be a non breaking change to the majority of use cases but may impact codebases that made assumptions that it would only be called in the error case. Additionally, error would either become optional, breaking, or an empty placeholder combined error, also not ideal.

2: Add a new parameter that accepts both error? and data? and deprecate the existing implementation. (https://github.com/FormidableLabs/urql/compare/main...crmitchelmore:urql:feat/auth-exchange-diderror-accept-data?expand=1)

**Comment by JoviDeCroock** [comment]
I personally don't really feel this is feasible because aside from always calling `didAuthError` the results in there aren't predictable which means all of a sudden you will be doing the following

```js
didAuthError: (res) => {
  const rootFields = Object.keys(res.data)
  if (res.data) {
    rootFields.forEach(...)
  }
}
```

Basically the shape isn't predictable so you would have to deeply check everything to see if you _ever_ encounter _some_ error and then check that error for being an auth one.

**Comment by crmitchelmore** [comment]
Yup, that's true. But if someone has implemented errors in this way, we don't have much choice!

At the moment we have an exchange that sits after authExchange already doing this.

If you have some idea of how else I could get it done I'll jump on it?

**Comment by JoviDeCroock** [comment]
My suggestion would have been to add an exchange that moves this on to the `errors` object but given your explanation you are already doing that😅

**Comment by crmitchelmore** [comment]
🤷‍♂️ thought it might be a long shot given no one else has requested this so far. Will be interesting to see if more people adopt this approach to errors in the future to give more weight to the requirement.

**Comment by kitten** [comment]
Referring to what @JoviDeCroock said here, I'll now close this as inactive.

To add a closing remark, for authentication signals, it's useful to use "global" API response errors, rather than resolver data, since they're signals that prevented a response outright for the `authExchange`, e.g.

- the token needs refreshing (non-destructive)
- the user needs to log in again
- the token is invalid (destructive)

whereas, when a resolver errors or when a union returns an "error-like" object, two things are often true:
- a union response for errors is cacheable and repeatable
- it only concerns one specific field

so I personally would say, this is an alternative approach that's more useful in _different situations_ rather than global errors. Specifically, when you want to display something that's unrelated to the API's general auth state for that user.
