### ISSUE TITLE
Refreshed auth is ignored in SSR'd queries

### ISSUE THREAD

**Issue by Nickersoft** [urql-graphql/urql#2836]
### Describe the bug

Hey folks,

I [reported this behavior](https://github.com/urql-graphql/urql/discussions/2716) awhile back as a discussion thread, seeing I didn't have a reproduction at the time, but now I do, so I thought I'd open this as an official issue 😅.  I've been seeing this behavior for quite some time in my SvelteKit app.

I'm trying to preload some of my queries via SSR before my page loads. However, my auth is cookie-based and deals with refresh tokens, so I'd expect that any backend queries (that use `.asPromise()`) would not resolve until the auth has failed, been refreshed, and then succeeded. 

Yet I'm noticing that while my access token cookie is refreshed, the query still produces an auth error and logs me out.

I've set up a reproduction in my own repo, as it's unfortunately a little involved:

1. Clone [this repo and this branch](https://github.com/Nickersoft/sveltekit-bugs/tree/nickersoft/urql-ssr).
2. In **both** the root directory **and** `backend`, run `pnpm install` (or whichever package manager you use).
3. In one terminal, inside `backend`, run `pnpm start`.
4. In another, in the root directory, run `pnpm dev`.
5. Open up `http://localhost:5173` (should be the default).
6. For both the CSR and SSR login buttons, click them to log in, wait 15 seconds, then refresh the page. 
    - For the CSR, you'll see that after 15 seconds, the auth expires, it makes a refresh request, then briefly shows `undefined` before showing the name `john` again as it refetches the data.
    - For the SSR, you'll see that after 15 seconds, it bounces you back to the login page. _However_, the server terminal will still log that the token has been refreshed, _and_ the page's cookie will have updated. Yet URQL still throws the error that redirects you.

I've been agonizing over this for weeks 😭 I've dug through the source code, and can't seem to uncover anything that would be a direct cause. Sometimes, depending on the cache policy, the error behavior can vary. Any help or guidance here would be appreciated. 

For now, I'm just making all my URQL queries client-side only.

### Reproduction

https://github.com/Nickersoft/sveltekit-bugs/tree/nickersoft/urql-ssr

### Urql version

@urql/core: "^3.0.5",
@urql/exchange-auth: "^1.0.0",
@urql/svelte: "^3.0.1",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
For simplicity's sake, I won't convert this back to a discussion ✌️ But, to keep it short, this is a bug in your implementation.

Specifically, there are two things going on, both related to your cookie authentication.

When you SSR and the refresh is performed, the cookie isn't used in the subsequent request.
This is happening here: https://github.com/Nickersoft/sveltekit-bugs/blob/d4fee0f271c236be209bd6a91b73b334d60d0b02/src/hooks.server.ts#L15

You're parsing the `SetCookie` header from your backend's response, but the token isn't used in the subsequent API request that your SSR server is performing. So, a natural and quick fix would be:

```diff
if (request.url.includes('graphql')) {
-  request.headers.set('cookie', event.request.headers.get('cookie') ?? '');
+  const accessToken = event.cookies.get('access_token');
+  request.headers.set(
+    'cookie',
+    accessToken ? `access_token=${accessToken}` : '',
+  );
}
```

Hence, using `event.cookies` that you've updated in the refresh request. This cookies register seems to preserve between requests in one SSR-session, so this works fine on the server-side.

The second issue then happens on the client-side. The issue is that your implementation relies on the SSR-session "impersonating" the user. In other words, when a server-side request is made, the server "takes over" the authorisation token and uses it like the client would. It then refreshes the token and — with the above fix — the client-side then takes over and...

The SSR data isn't correctly passed on (I believe, you're using `window.__URQL__` but haven't implemented a handover process which passes the SSR side's `ssrExchange` data to the client-side. So, it attempts to make the request again and doesn't do so with the new access token.

On the client-side, I see `REFRESHED: [...]`, which means that the code further doesn't pass the refreshed access token from the SSR process to the client. I believe, while you refresh SvelteKit actually takes over the caching of the SSR results.

This is basically where SvelteKit's caching of fetch responses conflicts with the `ssrExchange` approach. However, I believe, the cached first request is overriding the second one, which has the updated result. This might be because the state doesn't match up, which could be based on the cookie mismatch. I don't know enough about SvelteKit's rehydration process to tell you more about why this happens.

I can however see that SvelteKit correctly sends a `SetCookie` header on the HTML respone of SSR responses. This means that your `event.cookies` update is correctly translated into a cookie update on the SSR response.

This is good if you don't want to use the `ssrExchange` and bypass it. However, **you'll basically have to figure out why SvelteKit's `fetch` rehydration isn't working,** if you want to use SvelteKit's rehydration. Alternatively, using the `ssrExchange` correctly _would_ work, but would likely just duplicate SvelteKit's rehydration process.

Hence, let's remove the `ssrExchange` for a second, since you're not doing anything with it:

```diff
// layout.ts
			cacheExchange,
-			ssrExchange({
-				initialState: browser ? window.__URQL__ : undefined,
-				isClient: browser
-			}),
			errorExchange({
```

To recap again, I don't see _any_ fetch requests on the client-side when I refresh the SSR page, but I can confirm that at this point the server-side sees the correct result. In other words, I can see a correct result here on the server-side but not the client-side: https://github.com/Nickersoft/sveltekit-bugs/blob/d4fee0f271c236be209bd6a91b73b334d60d0b02/src/routes/ssr/%2Bpage.ts#L19

To further explain what's going on here, we now basically see that the client-side is _repeating_ the entire path that the server has done, but I also see that it's trying to do an auth refresh and then seeing an error in the subsequent GraphQL API request. All without _actually_ sending the request, implying that these are cached requests, including the `/refresh` request.

At this point, we'll basically have to look at why the client-side is making this cached `/refresh` call and get rid of it, so to make that change, let's ensure it _definitely_ uses the access token that the server-side gives it and never let `authExchange` make another request.

This is an **important** note. If you're using refresh+access token cookies, there's never any need to make a refresh call, ever. The API should _always_ be able to refresh the token independently, without a call to `/refresh`, so you may want to implement this mechanism, if you haven't already.

So, the last change is — in the absence of the above — that the client-side should _never_ make a refresh call and assume that SSR has already made this call: https://github.com/Nickersoft/sveltekit-bugs/blob/d4fee0f271c236be209bd6a91b73b334d60d0b02/src/routes/%2Blayout.ts#L31-L33

```diff
// layout.ts
				async getAuth({ authState }) {
-					if (!authState) {
-						return data?.accessToken ?? null;
-					}
+					if (browser && !authState && data?.accessToken) {
+						return data?.accessToken ?? null;
+					}

					const result = await fetch('http://localhost:3000/refresh', {
						method: 'POST',
						credentials: 'include'
					});
```

This is basically, I believe, a small flaw in how your `getAuth` is supposed to work. In short, it's called when authentication has failed and on initialisation. However, we only want `authState` to be initialised to `data?.accessToken` a) on the client-side, where the token is indeed available, and when `data?.accessToken` is available.

This is because, again, you're using a refresh auth mechanism with cached `fetch` requests on the client-side, and without `authState` actually mattering, since you're using cookies. So, while you may have to make `refresh` calls on the server-side, the client-side only has to _assume_ that after SSR the access token is correct. In fact, you could even just tell it that, when CSP isn't run, the token is correct.

I hope this helps, but in short, what I'd do, if you want to continue to use cookies, is to refactor the backend to perform refresh-auth opaquely. In other words, don't require a `refresh` call and ensure that you only error when the refresh has failed, and otherwise let the server-side take care of all the details of when to refresh the tokens, and send new ones using `SetCookie` (which presumably you're currently only doing on `/refresh`)
