### ISSUE TITLE
offline mode: asynchronous synchronization for request failure

### ISSUE THREAD

**Issue by ctesniere** [urql-graphql/urql#2882]
### Describe the bug

Hi 👋,

This bug is from urql/offlineExchange.

When I'm in offline mode :
I click several times on the "Click to simulate a new mutation" button. (see demo link)

When I'm in online mode :
the `flushQueue` function is call from [default-storage/index.ts](https://github.com/urql-graphql/urql/blob/232310fa528095a6e0214804e313e785dda742f1/exchanges/graphcache/src/default-storage/index.ts#L206-L211).

But, all failed queries (stored in metadata of indexedDB) are retried at the same time. Because we don't wait for the previous request to be finished.

https://github.com/urql-graphql/urql/blob/3dd23be7e41a2bd1db946f8626c6844fc5a1952c/exchanges/graphcache/src/offlineExchange.ts#L109-L110

This problem causes a risk of data loss, for example when modifying an input several times in offline mode.
In online mode, during synchronization, the mutation that will be the last to modify the value is random.

### Reproduction

Sorry, I don't have a graphql server for this test, but you can watch the network in the browser.

Source code : https://codesandbox.io/s/admiring-panini-yczq7c
Demo : https://yczq7c.csb.app/

### Urql version

"@urql/exchange-graphcache": "5.0.5"
"urql": "3.0.3"

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
> are retried at the same time. Because we don't wait for the previous request to be finished.

I think, this is essentially what you're highlighting? Keep in mind that it's useful for you to describe what you're expecting rather than describing what's happening.

In this case, I'll have to close this issue — sorry! While we don't have an exchange yet that's officially mantained, we've made some mentions to the following technique.
When you have several mutations that are all running concurrently, and you instead want to queue them up, and run some sequentially, we recommend to implement a custom exchange. Otherwise, you have to basically accept the default behaviour.

There's no way for us to impose any restriction on this by default. If we ran all mutations in series, that wouldn't make much sense for most users. If we only did this in some circumstances; that's, in my opinion, also an unexpected implementation.

Rather, that's why we'd want to be explicit about this. When it's not safe to run a mutation concurrently with others, it's never safe — `offlineExchange` in Graphcache or otherwise.

I'll for now close this as "won't fix" in its current state. But not to worry if I got something wrong here, I'm happy to of course reopen and come back to it as needed

**Comment by ctesniere** [comment]
Thanks @kitten for your answer.
Although I forgot to describe what I expect. You have understood that this concerns a sequential implementation.

I understand that we must keep the default behavior and that it is ultimately not a bug.

What do you think of a RFC, to make the flushQueue function customizable?

```ts
interface OfflineExchangeOpts {
  flushQueueAdapter?: () => void
}

const defaultFlushQueue = () => {
  ...
}

export const offlineExchange = <C extends Partial<CacheExchangeOpts & OfflineExchangeOpts>>(
  opts: C
): Exchange => input => {
  const { flushQueueAdapter, storage } = opts;
  ...

```

**Comment by ctesniere** [comment]
Thanks @kitten for your answer 👍 
Although I forgot to describe what I expect. You have understood that this concerns a sequential implementation.

I understand that we must keep the default behavior and that it is ultimately not a bug.

What do you think of a RFC, to make the flushQueue function customizable?
This will allow everyone to customize their own offlineExchange, which matches the description of URQL:

> The **highly customizable** and versatile GraphQL client for React, Svelte, Vue, or plain JavaScript, with which you add on features like normalized caching as you grow.
> https://formidable.com/open-source/urql/

A sample code that could customize the behavior of the foo method with the flushQueueAdapter option :

```ts
interface OfflineExchangeOpts {
  flushQueueAdapter?: () => void
}

let isFlushingQueue = false;
const defaultFlushQueue = () => {
  if (!isFlushingQueue) {
    isFlushingQueue = true;
    ...
    isFlushingQueue = false;
  }
}

export const offlineExchange = <C extends Partial<CacheExchangeOpts & OfflineExchangeOpts>>(
  opts: C
): Exchange => input => {
  const { flushQueueAdapter = defaultFlushQueue, storage } = opts;
  ...
  storage.onOnline(flushQueueAdapter);
}
```

What do you think ?
Is the flushQueueAdapter option a good direction? Or should we make a custom exchange?
