### ISSUE TITLE
Urql loses reactivity in vue on page route

### ISSUE THREAD

**Issue by vin-ni** [urql-graphql/urql#2935]
### Describe the bug

1. Run a urql subscription inside pinia store with reactive variable params
2. Go to page which displays query results + filtering results
3. Route to a different page
4. Route back to the page
-> the pinia reactivity breaks. Although updating the variables in the store, pinia doesn't update. 

Here's an excerpt of the code:
``` ts
import { defineStore } from "pinia";
import type { Ref } from "vue";
import { AllCountriesDocument } from "~/gql/queries/all-countries";
import { useClientHandle } from "@urql/vue";

export const useExampleStore = defineStore("example", () => {
  const uuid: Ref<string> = ref("");

  const code = ref("");

  const variables = computed(() => {
    return code.value ? {filter: {code: {eq: code.value.toUpperCase()}}} : {}
  })
  
  const urql = useClientHandle();
  
  const { data, fetching } = urql.useQuery({query: AllCountriesDocument, variables})
  

  return {
    uuid,
    code,
    data,
    fetching
  };
});
```

Somehow `data` is not updating after routing.

https://user-images.githubusercontent.com/9806572/214361855-ebbfd88e-a510-4881-bcb5-500f635f585f.mov

### Reproduction

https://github.com/vin-ni/nuxt3-urql-routing-bug

### Urql version

@urql/vue 1.0.4

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I'm going to say right off the bat that I can't guarantee that we can accept this issue or support this pattern, since the following is sketchy to me:

```js
defineStore("example", () => {
  const urql = useClientHandle();
  
  const { data, fetching } = urql.useQuery({query: AllCountriesDocument, variables})
  // ...
});
```

Specifically, last time I checked, Pinia stores are not able to provide `useQuery` the necessary hooks to register on subscribe calls.

I'm also debating converting this to a discussion, sorry! 😅 I'll let you know and will let you respond first, but while we have multiple GH Discussion threads re. Pinia (some containing disclaimers regarding it) we _don't_ explicitly support this pattern and can currently only defer to the Pinia team, because otherwise we'd have to likely specifically change code to suit their stores

**Comment by vin-ni** [comment]
Hmm, 
I posted, because there wasn't really an answer in the other discussions. Basically it seems it is not possible to have a continuous subscription within a pinia store. (https://github.com/urql-graphql/urql/discussions/2422#discussioncomment-3999680).

What surprises me, is that the pinia store doesn't get unmounted, does it? It's generated by the first component that uses it and stays alive during the session. How come it unmounts the `useQuery`?

I definitely need a subscription. Maybe I should ask at Pinia then.

**Comment by vin-ni** [comment]
@kitten I found a new way of implementing it. Instead of using `@nuxt/pinia`, I wrote a custom plugin, that initiates the store and keeps it alive. Could you take a quick look and let me know what you think?

https://github.com/vin-ni/nuxt3-urql-routing-bug/tree/custom-plugin

### Plugin Code
``` ts
import { createPinia } from "pinia";
import { defineNuxtPlugin } from "#app";
import { useExampleStore } from "@/stores/exampleStore";

export default defineNuxtPlugin((nuxtApp) => {
  const pinia = createPinia();
  nuxtApp.vueApp.use(pinia);

  nuxtApp.hook("vue:setup", () => {
    const exampleStore = useExampleStore();
    nuxtApp.exampleStore = exampleStore;
  });
});
```

### Component Code
```ts
import {useNuxtApp} from "#app";
import { storeToRefs } from "pinia";
const nuxtApp = useNuxtApp();

const exampleStore = nuxtApp.exampleStore;
const { code, data, fetching} = storeToRefs(exampleStore);

```

**Comment by productdevbook** [comment]
https://github.com/vin-ni/nuxt3-urql-routing-bug/blob/main/plugins/urql.ts

after pinia store used.

```ts
import { defineStore } from 'pinia'
import type { MeQuery } from '~/graphql/schema'
import { MeDocument } from '~/graphql/schema'

export const useUserStore = defineStore({
  id: 'userStore',
  state: () => ({
    me: {} as MeQuery['me'],
    newUser: false,
    admob: false,
  }),
  getters: {
  },
  actions: {
    async onInit() {
      await this.getUser()
    },
    async getUser() {
      const { query } = useNuxtApp().$urql
      try {
        const { data } = await query(MeDocument, {}).toPromise()
        if (data) {
          this.me = data.me
          return data.me
        }
      }
      catch (error) {
        this.newUser = true
      }
    },
  },
})

```

**Comment by kitten** [comment]
I totally forgot about this, sorry!

So, three notes for future readers:
- You can always subscribe to a `client.query` manually (or a store that is). That means though that it'll never become inactive, so it'll be continuously updating and fetching new data for that query, even if you app doesn't currently need that data. Generally, I would simply advice people to stick to treating GraphQL data as just data, and not state. In most cases that yields a better outcome in your apps' structures (as in, one query per page). That said, there are obviously exceptions
- I don't really know what `nuxtApp.hook` does for the invalidation, but it likely doesn't invalidate. If you only use it for truly global data however, that could of course be fine.
- To address the above directly (@productdevbook), the problem with just doing `client.query(...).toPromise` is that you lose all update capabilities. Of course, you're free to add one-off promises where needed but those queries will never update, since a promise can only resolve once. Therefore, that's highly discouraged if you need that data to update

I'm closing this for now, as per the last comment ✌️ I think we have enough notes in here now for alternative solutions and to point out the caveats.

Again, to point out the most important realisation here from @vin-ni:

> What surprises me, is that the pinia store doesn't get unmounted
