### ISSUE TITLE
(graphcache): Writing to the cache fails during cache read operations

### ISSUE THREAD

**Issue by PrescottJRynewicz** [urql-graphql/urql#2977]
### Describe the bug

# Context
I am migrating an app from REST to GraphQL with URQL. I have run into a situation where calling `cache.invalidate` is throwing an undefined error in [data#setNode](https://github.com/urql-graphql/urql/blob/main/exchanges/graphcache/src/store/data.ts#L265). 

I am attempting to invalidate a paginated query response in a separate resolver. Here is the basic flow

## Reproduction

1. Query for a page's data, which includes a relay-compliant list of data. 
2. Create a ref to a specific field resolver in another query that is not linked to the paginated list result. When this value changes, we need to invalidate the list. We can't do this in a mutation because we are migrating to GraphQL, and the operations that would invalidate our list are not in the graph yet. When this ref changes, we know that the values in the list have changed.
3. In a simple `number` field resolver, I check if the resolved value from `parent.value` is different from the ref, and then call
    ```
    cache.invalidate(
        'Query',
        cache.keyOfField(...)
      );
    ```

When calling invalidate, `setNode` has `currentOptimisticKey` set, but `map.optimistic` is empty.  

### Reproduction

https://www.loom.com/share/d70f14f8dd76430190ed425e334210d4

### Urql version

3.0.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Ah, I see what's going on here!

This isn't currently well documented, but _updating_ the cache (i.e. calling `cache.updateQuery`,, `cache.writeFragment`, or `cache.link`) is not supported inside `resolvers`. We really should've added an invariant for this a while ago but I suppose that's now on the top of my list to prevent this confusion.

Basically, there's two separate "phases" that the cache can be in: a query, or a write. This is represented in the code in these two separate files:
- [`exchanges/graphcache/src/operations/write.ts`](https://github.com/urql-graphql/urql/blob/34f83b14af9531f0335cd1c9d9fa3bfc8a6835a1/exchanges/graphcache/src/operations/write.ts)
- [`exchanges/graphcache/src/operations/query.ts`](https://github.com/urql-graphql/urql/blob/34f83b14af9531f0335cd1c9d9fa3bfc8a6835a1/exchanges/graphcache/src/operations/query.ts)

And this is actually stored in the `data.ts` file (i.e. the data layer) as `OperationType` in [`currentOperation`](https://github.com/urql-graphql/urql/blob/34f83b14af9531f0335cd1c9d9fa3bfc8a6835a1/exchanges/graphcache/src/store/data.ts#L62)

Basically, the data layer is only ever ready to _either_ read or write. The reason for this is twofold. When we're writing to the data layer, the `cacheExchange` is ready to then add on more updates to other queries, reacting to any operation having updated its data. When it's reading its either reading back an operation against the cache after a server result, or it's querying from the cache in reaction to a subscriber to the `Client` asking for it (i.e. an operation being triggered in `urql`)

In other words, separating these two stages is because:
a. the `cacheExchange` isn't built to add on updates to other queries after a **cache read**, because a **cache read** is never expected to have side-effects
b. the data layer is reading from a specific layer, so updating at the same time as reading is a bit risky, because we never know whether we have to go "back" to read again

Addressing `a)` would be possible, but I don't think we actually have to.

---

Your goal is basically to say "if field X updates, update field Y".
However, the `updates` config that is responsible for this behaviour, is currently limited to `Mutation` and `Subscription`: https://github.com/urql-graphql/urql/blob/34f83b14af9531f0335cd1c9d9fa3bfc8a6835a1/exchanges/graphcache/src/types.ts#L182-L189

We've had prior discussions to change this, but it also allows for some questionable patterns in a GraphQL cache, so we refrained from implementing this before we had a necessary use-case.

However, I believe your use-case warrants this, so we should get this limitation lifted.

In short, I think, in reaction to your issue we should do two things:
- Lift the limitation on `updates[typeName]` to allow for any type to have programmatic updates
- Add development invariants to `store.{writeFragment,updateQuery,link}` to prevent them from being called during a "read" operation.

How does that sound to you?

**Comment by PrescottJRynewicz** [comment]
@kitten sounds great! I had a hunch writing to the cache in resolvers was going to be an invariant 

The proposed updates solution makes sense to me - will review the PR when I get to my keyboard shortly 👍

**Comment by kitten** [comment]
Just to update, #2979 will take a little longer. I'll have to find a way to resolve a situation where `resolvers[type]` takes root names from the passed schema, but `updates[name]` always only accepted `"Mutation"` and `"Subscription"` ignoring the root names. This basically means that it's hard to pull this off without breaking changes

**Comment by PrescottJRynewicz** [comment]
@kitten sounds good - let me know if I can provide support.  

Would you mind reviewing [this comment](https://github.com/urql-graphql/urql/pull/2979#discussion_r1117247276) to confirm my understanding of the changes?
