### ISSUE TITLE
Subscription closed after 3 events

### ISSUE THREAD

**Issue by wnederhof** [urql-graphql/urql#3139]
### Describe the bug

When using next-urql `^5.0.0` and urql `^4.0.0` instead of next-urql `^4.0.3` and urql `^3.0.3`, in combination with graphql-sse `^2.1`, my subscription closes when the third event comes in. The version of graphql-sse does not make a difference.

The setup:

```
export default withUrqlClient((ssrExchange) => {
  const exchanges = [
    dedupExchange,
    cacheExchange,
    ssrExchange,
    fetchExchange,
  ]
  if (typeof window !== 'undefined') {
    const sseClient = createSseClient({
      url: 'http://localhost:8080/subscriptions',
      credentials: 'include',
    })
    exchanges.push(
      subscriptionExchange({
        forwardSubscription: (operation) => ({
          subscribe: (sink) => ({
            unsubscribe: sseClient.subscribe(
              {
                query: operation.query as string,
                variables: operation.variables,
              },
              sink
            ),
          }),
        }),
      })
    )
  }
  return {
    url: 'http://localhost:8080/graphql',
    exchanges,
    fetchOptions: {
      credentials: 'include',
    },
    requestPolicy: 'cache-and-network',
  }
})(App)
```
Other than that, I'm simply using `useSubscriptions` with no bells or whistles.

### Reproduction

Not sure how to do that with a subscription and gql-sse

### Urql version

next-urql ^5.0.0
urql ^4.0.0
graphql-sse ^2.1.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
Are you sure you're using the latest version `4.0.4` of `@urql/core` with this fix? https://github.com/urql-graphql/urql/pull/3137

Because this exact bug has already just been reported and fixed 😅

**Comment by mnichols** [comment]
Thank you for this @kitten ..I confirmed this fixed the same bug I was about to come out and report! I had to be sure to install @urql/core along with @urql/svelte to be sure to use the latest (`4.0.4`).

**Comment by kitten** [comment]
@mnichols: Yes, just to clarify — although, this should also be documented in the TSDocs — `fetching` (no matter the API, no matter the binding) is basically UI state that means that data is expected. So, for `useQuery` or `queryStore` it means that new data is expected.

`stale` means that new data is being fetched in the background and that's a derived state from the `Client` or an exchange, like the normalised cache, or the non-normalised document cache.

`hasNext` is an API-driven flag and is set directly by the transport, e.g. the `fetchExchange` or any `subscriptionExchange`. For subscriptions — which is what the fix was for — it by default is set to `true`, and means that the transport will _deliver_ new results, so that's directly set on your server-side schema, although transports like `graphql-ws` may not actually set it, since it's part of the future Incremental Delivery change
