### ISSUE TITLE
cache issues when using `@defer` directive and `@urql/exchange-graphcache` 

### ISSUE THREAD

**Issue by beerose** [urql-graphql/urql#3161]
### Describe the bug

I’ve run into a pretty weird issue while using urql and I could really use some help.

The main problem is that when my app sends a query with defer or when it receives chunked data, it seems to be the last request that’s ever fired.

For example, when I open my app and navigate through random pages, everything works just fine. But when I go to a page that uses defer and then move to another random page, I get a bunch of runtime errors due to missing data. It looks like the query was resolved (cache hit), but an API request was never fired. When I refresh the page, everything works again.

After some debugging, I narrowed it down to have something to do with `@urql/exchange-graphcache` (if I remove the exchange it works fine). Based on the logs and urql devtools, there’s a cache hit for those queries when I there shouldn’t be. Also, when I remove defer usage, logs from the same flow show cache misses.

Do you have any suggestions what could be causing this?

Urql dev tools:
* There's no API call for the last four queries
* The fifth one (from the bottom) is the one with `defer` directive
<img width="859" alt="CleanShot 2023-04-18 at 17 01 19@2x" src="https://user-images.githubusercontent.com/9019397/232907214-8ef31d6e-5d4b-4f17-9f1a-fbb57ea868d0.png">

<img width="474" alt="CleanShot 2023-04-18 at 17 02 33@2x" src="https://user-images.githubusercontent.com/9019397/232907145-6642de26-261e-4a5f-9bff-b6d51d74972b.png">

Here's a PR to GraphQL Hive with adding defer to one of the queries (and necessary setup): https://github.com/kamilkisiela/graphql-hive/pull/1964

### Reproduction

https://github.com/kamilkisiela/graphql-hive/pull/1964

### Urql version

@urql/core: 4.0.4

@urql/exchange-graphcache: 6.0.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This is a great description btw :+1: If I could have every bug report in this format, I'd be happy beyond belief haha

Some follow-up questions before I look into this tomorrow, are you navigating before the deferred query completes? Does the bug happen either way? I basically realised just now that we have no test case covering this.

Also to clarify, I'm not sure, off of a cursory glance whether I could reasonably run the entire GraphQL Hive API and UI just to reproduce this, so, unless this is really simple, I'd carefully point out and hazard a guess that I'll have to start looking at this without a reproduction at first. There's not a lot of code-paths for `@defer` however, so that should be alright

Lastly, can you confirm for me please that the cache hit response you're getting has the deferred fields null'ed out rather than missing? I'd assume that that's a prerequisite for this being marked as a hit, but I may be wrong, depending on where the bug is located.

Best case, this is an old regression from the deep-diffing code that keeps results reference equal 🤔

**Comment by BitPhinix** [comment]
Still experiencing the same issue!
