### ISSUE TITLE
RFC: Graphcache support changing `__typename` component of the cache

### ISSUE THREAD

**Issue by zwade** [urql-graphql/urql#3176]
## Summary

The format for keys in the graphcache index is `<__typename>:<id>`. The `id` component is a bit ambiguous, as different apis will use different identifiers. Consequently, graphcache allows specifying a `keys` field on the options object that allows users to override how that id portion is computed for the key.

However, there is no way to do the same for the `__typename` component. This makes sense -- it is a standard part of the GQL api and there's little reason to override.

Unfortunately, the current caching model has no internal notion of inheritance (or unions). What this means is that if we have a resolver that returns `Car` whose two inhabitants are `FourWheeler` and `TwoWheeler`, a `FourWheeler` with id `123` will be cached as `FourWheeler:123`. 

Now let's say we have a mutation that unceremoniously rips the back two wheels off our car and returns it to the frontend. The id remains `123` and the entity is still a `Car`, but the underlying `__typename` would change to `TwoWheeler`. Graphcache will see this and insert a **brand new** cache entry called `TwoWheeler:123`, and not update the status of `FourWheeler:123`.

In a perfect world, this feature request would be to include better handling of that (maybe by generating multiple cache keys for each type and then having a separate type of link that joins them? not sure -- out of scope here).  However, there is a much simpler solution that handles the 95 percentile of cases (at least, that I personally encounter).

## Proposed Solution

Even if graphcache isn't really able to understand what the relationship between elements of a common inheritance structure is, the programmer does. In the same way that we are allowed to use the `keys` option on graphcache to re-key (really re-id) a record, we could also expose a `typenames` option that let's us "re-type" a record.

I don't know if this is a perfect solution. It really only works if cache keys are write-only (i.e. never parsed). As far as I can tell, this is the case, but I only gave a cursory glance.

For what it's worth, I've implemented this naive solution for our codebase, and so far it seems to be working exactly as expected. However I would love to hear the thoughts of the maintainers on whether this is a feasible (and safe!) solution. 

## Requirements

For me personally, the primary requirement is that I can use mutations that safely re-type an entity of a given inheritance chain (or union) and have the cache keep the link between it and previous versions.

## POC

https://gist.github.com/zwade/64b96dea8b483720be32eba51713a8bc

**Comment by kitten** [comment]
We've got some issues/discussions floating around with this explanation, I believe, but to keep it short, I think, it's very unlikely for us to implement this, partly because it pushes complexity in an unreasonable direction for Graphcache to not be able to make assumptions (or rather, even less assumptions) about the data and data structure, which then in turn blocks other features,
and, in part; because it encourages patterns that I (at least personally) wouldn't want to encourage, in terms of the mental model of how to model and design a schema.

To put it short, GraphQL actually also doesn't have a notion of inheritance, and rather it explicitly has a model of interfaces that can be chained. This is actually a bigger different than it seems. While unions and interfaces are often combined to model inheritance, I think it often leaves out some convenient affordances that GraphQL provides.

Let's suppose, we've got an interface `CarLike` and two implementors, `TwoWheeled` and `FourWheeled`. `FourWheeled` and `TwoWheeled` are further an implementor of `TwoWheeledLike`.
A field could now either return `FourWheeled`, an interface, or a union of concrete object types.

The existence here of concrete object types is important. To put it differently, ultimately, a result must of course always resolve to concrete object types, i.e. one ambiguous object type.

However, let's say you would enable `FourWheeled` to turn into `TwoWheeled`. Now, in your cache implementation, you're basically "downleveling" the type and all references to it can legally change to `TwoWheeled`.

However, what if the type turns from `TwoWheeled` into `FourWheeled`?
This is still legal. After all, we can "complete" the type to fit the "extended" object.
If we allowed this then we'd also have to assume that either:
- all references to the "upleveled" `FourWheeled` type are now invalid where `TwoWheeled` is used and have to be invalidated
- or, all references are still kept but there's no guarantee they'll match types, so matching in the future may fail
- or, all references are deleted no matter how they change, which brings you back to the problem you describe

In short, in GraphQL’s type system of interfaces and unions being returned by fields, even if everyone included unambiguous schema information on the client-side (which we wouldn't ask people to have to do of course 😅 hence, it's optional) there's still some ambiguity in wanting objects to "change" type.

This is partially solved by letting objects have a globally unique ID (like Relay enforces). But that's a requirement for the API, and, I suppose, we could allow this at least in the future, since that's a smaller change and switch.
However, the above limitations still apply. There's no way of knowing whether this is legal, and there's no way for a user to specify that only _some_ relations are affected if an object changes types.

**How does one get around this?** — and this is something that I think is underrated.

I'd recommend `Edge` types for this. An `Edge` type can have a unique type and can reference an interface on the server-side schema. However, what it also allows us to do is to change what's referenced globally, wherever this `Edge` is used.

So, let's say you want an object to "change type". If that object is already written, you can switch every matching edge over to this new type, especially if it has a matching `id` field.

This is such a subtle but powerful change in schema modelling, because you detach your constraint of how types can change "one away". Now, instead of pointing at `TwoWheeledLike`, for example, your schema could use a `TwoWheeledLikeEdge` type and a `FourWheeledLikeEdge` type. If a `TwoWheeled` object is replaced or turns into a `FourWheeled` like object, you can switch the matching `TwoWheeledLikeEdge` over without having to actually care about the "legality" of it, and vice versa.

So, in short, I often recommend people to look into edge types when getting into scenarios where links between objects "switch" between different types, or where the _relation_ between objects needs to be addressed globally

**Comment by zwade** [comment]
Hi! Thank you so much for the in-depth response. I appreciate that the team has spent a lot of time thinking about this. 

If you're able, I'd like to follow up to make sure I understand the nature of the `Edge` suggestion.

Let's say for the sake of this discussion that we have the following (naive) GQL schema

```gql
interface Car {
  id: ID!
  color: String!
  numWheels: Int!
}

type TwoWheeler implements Car { ... }
type FourWheeler implements Car { ... }

type query {
  myCars: [Car!]!
}

type mutation {
  truncateCar(id: ID!): Car!
}
```

And then we convert it to an edge-oriented schema as such:

```gql
# `Car`, `TwoWheeler`, and `FourWheeler` unchanged

type CarEdge {
  id: ID! # Same as the node's id
  node: Car!
}

type query {
  myCars: [CarEdge!]!
}

type mutation {
  truncateCar(id: ID!): CarEdge!
}
```

I can understand how this would solve my direct problem -- even if the type of the `Car` changes as a result of `truncateCar`, the `CarEdge` would serve as a pointer to the car that can forcibly invalidate any query that returns it when the type changes.

In other words, switching to this model would allow for safe caching in the following sequence of queries (assuming I have one `FourWheeler` with id `"1"`: 

```gql
query getMyCars {
  myCars {
    id
    node {
      id
      color
      numWheels
    }
  }
}

# Some time later

mutation sliceAndDice {
  truncateCar(id: "1") {
    id
    node {
      id
      numWheels
    }
  }
}
```

Once the mutation is called, the linkage that previously existed from `CarEdge:1` to `FourWheeler:1` would be updated to `TwoWheeler:1`. The first query would recognize that its gone stale, and re-execute. 

This is correct behavior, but it requires refetching all of the data from the query. In this particular example I've specifically only fetched data off of the `Car` interface. Since the edge in question is itself a `Car` edge, my desired outcome would be for the mutation to simply update the cached records in place.

However, since the caching key of the record changes, this seems like a non-starter (regardless of schema architecture). Is there an alternate handling of edges (or of the caching system) that bypasses this problem?

Thanks again so much for the help, and for your work with URQL!

**Comment by zwade** [comment]
Awesome, yeah this makes a lot of sense. I think you're right and that it would be worthwhile for us to reevaluate our schema to allow for more modular updates like the ones you're suggesting. 

I am a bit curious however, if the pattern of "make the common data query-able on the edge," or the more generic form of "model inheritance as a multi-level object" is a common pattern? It's not one that I've come across, but I am also far less exposed to others' GQL schemas 😅 

Otherwise thank you so much again for the help. For now I think i'll do a manual cache invalidation on the offending mutations (fortunately there aren't many), and then re-evaluate how we're modeling our schema moving forward!

**Comment by lukereative** [comment]
Just chiming in here because I've come up against this issue, unfortunately it would be very hard for me to implement 'Edge' types on the Graphql provider that I am using. Thanks for your in depth explanation though.

The suggestion of either global IDs or cache enumeration would work for my use case with that latter I think be the more flexible of the two.
