### ISSUE TITLE
sourcemaps are generated incorrectly (exchange-graphcache)

### ISSUE THREAD

**Issue by bosycom** [urql-graphql/urql#3182]
### Problem
Trying to debug `cacheExchange`:
```typescript
import { cacheExchange } from "@urql/exchange-graphcache";
// ...
const cache = cacheExchange({});
```

loads `urql-exchange-graphcache.mjs` and its `.map` file in Chrome dev tools, but breaks in the middle of a comment in line 60 of `/exchanges/graphcache/src/cacheExchange.ts` in my app.

Additionally, to check that it is not necessarily just an issue with my setup, I used source map visualizer here from https://sokra.github.io/source-map-visualization/#custom
I uploaded the files and came to the same result as can be seen here:

![image](https://user-images.githubusercontent.com/10790842/234359207-659990d8-691b-45d7-80b1-704209c7f418.png)

Are source maps generated incorrectly?
Any help is appreciated which would help me on my way to understand graphcache better.

**Comment by kitten** [comment]
Hiya :wave:
I'll have to have a look at this tomorrow. Quick note on this, I'd assume that something's still off with our original file sources in the source map itself or the Rollup generation of them. We had an issue not too long ago where the inclusion of the `typescript` plugin (or any other plugin that uses `typescript`) would prevent sourcemaps from being generated correctly 🤔 

However, I assumed that removing the TS plugins entirely from our build chain would've resolved this. https://github.com/urql-graphql/urql/blob/35c97ccca65470f25cc1295d78e18aaab4d2f6ef/scripts/rollup/plugins.mjs#L21-L42

I assume that there's still an underlying issue that prevents them from working correctly, so I guess we'll have to investigate this further.

On a side note, if you need any more information on how Graphcache works and such, feel free to send me questions [over on the Discord directly](https://urql.dev/discord), since that may be quicker for you than to sift through what you're looking for. I also have a higher level explanation of it [in a blog post](https://kitten.sh/graphql-normalized-caching), however, some newer parts aren't covered in there
