### ISSUE TITLE
Duplicated requests even for older queries using `requestPolicyExchange` with 6.1.5-canary

### ISSUE THREAD

**Issue by frederikhors** [urql-graphql/urql#3319]
### Describe the bug

@kitten, as usual [I cheered too soon](https://github.com/urql-graphql/urql/discussions/3304#discussioncomment-6491675) before discovering ONE DIFFERENT PROBLEM probably brother of the other.

Steps:

1. Start the backend visiting: https://codesandbox.io/p/sandbox/h1pcl

1. Open the frontend reproduction: https://stackblitz.com/edit/sveltejs-kit-template-default-y5hteh

1. Go to "List"

1. Wait for the list to appear

1. Open browser Dev tools on the "Network" panel

1. Click on the button "Complete" on one todo

1. The first call starts and after some seconds it finishes

1. AND NOW THE NEW PROBLEM (with `"6.1.5-canary-7ddccc13"` at least):

1. Another call starts! For every action, even if you click on the "Add more random todos" button.

I'm sad again! :LOL:

### Urql version

```
"devDependencies": {
	"@sveltejs/adapter-auto": "2.1.0",
	"@sveltejs/kit": "1.22.3",
	"@urql/core": "4.0.11",
	"@urql/exchange-request-policy": "1.0.2",
	"@urql/exchange-graphcache": "6.1.5-canary-7ddccc13",
	"@urql/exchange-persisted": "4.0.1",
	"@urql/exchange-retry": "1.2.0",
	"@urql/svelte": "4.0.3",
	"prettier": "^2.8.0",
	"prettier-plugin-svelte": "^2.10.1",
	"svelte": "3.59.2",
	"svelte-check": "3.4.6",
	"svelte-preprocess": "^5.0.4",
	"tslib": "2.6.0",
	"typescript": "5.1.6",
	"vite": "4.4.4"
},
```

### Gif
![iss](https://github.com/urql-graphql/urql/assets/41120635/7d36438b-5080-4379-88b7-b02dd1312a71)

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by frederikhors** [comment]
Sorry. I think it was the `requestPolicyExchange` which I don't need.

**Comment by frederikhors** [comment]
I think this deserves your checking, @kitten. Because it is strange what is happening.

Even though I'm using `requestPolicyExchange` I think I don't have to reload queries I'm not calling:

```ts
requestPolicyExchange({
  ttl: 1,
  shouldUpgrade: (e) => {
    console.log("test, e:", e);
    return true;
  }
}),
```

**Comment by kitten** [comment]
This is expected behaviour.
You've set the `requestPolicyExchange` to `ttl: 1`, which practically means that every operation will be upgraded to `cache-and-network`. This in turn means that when the todo list is refreshed after the mutation, its operation is upgraded to `cache-and-network`

You can even see in the network tab that it's the list query after:

<img width="309" alt="Screenshot 2023-07-20 at 11 46 44" src="https://github.com/urql-graphql/urql/assets/2041385/8d4f0806-2aa8-4483-9ed7-e8cd69d3d645">

<img width="309" alt="Screenshot 2023-07-20 at 11 46 37" src="https://github.com/urql-graphql/urql/assets/2041385/bbaaabdb-fd81-448f-b6c2-d1246c68e769">

If you increase the TTL, the new request will not be made until the TTL is expired

**Comment by frederikhors** [comment]
I thought the `requestPolicyExchange` was only for queries that the user triggers, not for queries that have already finished. In this case the list query is already finished and so I thought it would hang until I call it (and in that case it checks the TTL).

Okay. Now I understand that this exchange operates differently.
