### ISSUE TITLE
RFC: @urql/vue - Allow getter syntax in `useQuery`

### ISSUE THREAD

**Issue by Neluji** [urql-graphql/urql#3556]
## Summary

In Vue, if we use component props in the `variable` object of the `useQuery` composable, their reactivity is lost in the process and this results the same as if it was passed as a constant. To avoid this, the solution is to wrap the `variable` object in a `toRef`, using a getter function.

Allowing to pass directly the getter function to the `variable` property, as VueUse is doing with their [`MaybeRefOrGetter`](https://github.com/vueuse/vueuse/blob/main/packages/shared/utils/types.ts#L37) type, would be more fluent.

## Proposed Solution

Check if the passed `variable` arg is a function, and if yes, unwrap it when needed (see [VueUse `useFetch` composable](https://github.com/vueuse/vueuse/blob/1558cd2b5b019abc1feda6d702caa1053a182903/packages/core/useFetch/index.ts#L436) and [how they does it](https://github.com/vueuse/vueuse/blob/1558cd2b5b019abc1feda6d702caa1053a182903/packages/shared/toValue/index.ts#L9)?)

**Comment by kitten** [comment]
Sorry, I forgot about this.
Just to clarify, we don't use Vue ourselves regularly, so we're happy to receive PRs for it (same as for anything really — as long as it's not a heavy RFC that we may not accept, which isn't the case here of course)

Because we don't really have a lot of Vue projects to test against, I'm not 100% convinced that this works, and don't have enough context to test the getter-based reactive primitives in action.

**Comment by kitten** [comment]
@Neluji I've just merged the PR, which means that the `@urql/vue` package with the PR's changes should be available now as a pre-release. That's published as `@urql/vue@1.2.0-canary-9bf3289b`, which you should be able to install and test using the `@urql/vue@canary` tag.
