### ISSUE TITLE
@urql/exchange-graphcache returns empty data & error although fetch response contains valid data. (when same entity is requested in parallel)  

### ISSUE THREAD

**Issue by farin** [urql-graphql/urql#3562]
### Describe the bug

Running three queries.
First Q1 fetches some entity. 

Then in paralel, Q2 and Q3 fetches another attributes on same entity.
In some approx 20% or cases a race condition occurs and Q3 query subscription returns empty result and nothing else.
{data: null, errors: undefined}

On network layer I can see all data are returned from server correctly but query.subscribie never emit them (instead null data is emitted once)

I isolated issue, used fetch mock and make example with reproducible example where issue happens always.

Some observations:
When cacheExchange is not used then everything is fine.
When schema was changed and attributes was moved to different entity then both queries are also always correct.
When Q2 is not executed, then Q3 resolves as expected. 

### Reproduction

https://github.com/farin/graphcache-bug

### Urql version

@urql/core 5.0.0
@urql/exchange-graphcache 7.0.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This issue is expected, you are returning different data for the same field at different times, this is the query you do multiple times

```graphql
query { me { id } }
```

This is dispatched three times, 2/3 times this returns a `__typename` of `UserType` and an identifier of `1`. 1/3 times this returns the same `UserType` but with a different identifier of `2`. In a normalized cache this is illegal because `Query.me` is pointing at `UserType:1` and then gets clobbered with `UserType:2` and again with `UserType:1` this is expected to fail.
