### ISSUE TITLE
SSE headers are being sent for all requests

### ISSUE THREAD

**Issue by mattjohnsonpint** [urql-graphql/urql#3673]
### Describe the bug

Consider the following code in urql core:

https://github.com/urql-graphql/urql/blob/b9f34fd19ee5f9022db4d2f9eb610943c787dac1/packages/core/src/internal/fetchOptions.ts#L149-L154

Line 152 makes sense, but line 153 _also_ includes `text/event-stream, multipart/mixed` accept headers, even though the operation is not a subscription.

I'm not sure about `multipart/mixed`, but at least for `text/event-stream`, that recently created a problem for us on our backend with the latest GQLGen release for Go.  I reported that bug to them here: https://github.com/99designs/gqlgen/issues/3275.  But I think this is one of those things that has problems on both sides.

Does it at all make sense to accept an event steam for non-subscription operations?  If not, then it probably should be removed from those requests.

### Reproduction

Any of the examples will reproduce this. Just make a request and examine the outbound Accept HTTP request header.

### Urql version

@urql/core 5.0.6

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Hey @mattjohnsonpint 

For the [Incremental Delivery](https://github.com/graphql/graphql-wg/blob/main/rfcs/DeferStream.md) protocol both `text/event-stream` as well as `multipart/mixed` are used currently for an HTTP transfer. We decided that it's better to opt-in to this behaviour rather than opting out.

I do hear your concern and luckily we can work around that by overriding `fetchOptions` on your urql-client:

```js
new Client({
  fetchOptions: () => ({ accept: 'application/graphql-response+json, application/graphql+json, application/json' })
})
```

Or if you need the operation in-scope you can use our [`mapExchange`](https://commerce.nearform.com/open-source/urql/docs/api/core/#mapexchange) to do the following

```js
mapExchange({
  onOperation: (operation) => {
    const existingFetchOptions = operation.context.fetchOptions
    const newFetchOptions = {
      ...(typeof existingFetchOptions === 'function' ? existingFetchOptions() : existingFetchOptions || {})
      Accept: ''
    }
    return makeOperation(operation.kind, operation, {
      ...operation.context,
      test: true,
    });
  }
})
```

**Comment by mattjohnsonpint** [comment]
Thanks for the workaround and explanation. 👍
